#Ler um input e mostrar o tipo e todas as informações

dado = input('Digite algo: ')
print(type(dado))
print('alfanumérico: ', dado.isalnum())
print('alfabeto: ', dado.isalpha())
print('ascii: ', dado.isascii())
print('dígito: ', dado.isdigit())
print('caixa baixa: ', dado.islower())
print('decimal: ', dado.isdecimal())
print('identificador: ', dado.isidentifier())
print('numérico: ', dado.isnumeric())
print('caxia alta: ', dado.isupper())
print('imprimivel: ', dado.isprintable())
print('espaço em branco: ', dado.isspace())
